# Generated by Django 4.2.3 on 2023-08-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
