# Generated by Django 4.2.3 on 2023-07-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_user_is_admin_user_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keywordCount',
            field=models.IntegerField(default=0),
        ),
    ]
