# Generated by Django 4.2.3 on 2023-10-15 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('user', '0002_remove_userkeyword_usersite_userkeyword_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeyword',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category'),
        ),
        migrations.AlterField(
            model_name='userkeyword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
