# Generated by Django 4.2.3 on 2023-10-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userkeyword_category_alter_userkeyword_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interval',
        ),
    ]
