# Generated by Django 4.2.3 on 2023-09-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interval',
            field=models.IntegerField(default=0),
        ),
    ]
